version: '3.8'

services:
  db:
    image: postgres:15.10
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: multi-project
      POSTGRES_USER: sv_user
      POSTGRES_PASSWORD: sv_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4:8.14.0
    container_name: pgadmin
    ports:
      - "8081:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@svshayt.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - db
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network: